### ISSUE TITLE
Remove debug code in production code

### ISSUE THREAD

**Issue by pke** [hirokazutei/react-native-spacing-system#81]
Thanks for implementing this! No more fiddling with margins and paddings!

I wonder if we could wrap all the debug code into `__DEV__` to get it removed in production builds?

**Comment by hirokazutei** [comment]
Hello @pke,
Sorry for the late reply.

From what I understand, you are suggesting to remove `debug` and `debugOptions` from the production build of the library, is that correct?

The sentiment behind debug is meant for devs to debug their own component's spacing. Especially useful when used with things like `storybook`.

If that isn't what you meant, let me know which unnecessary debug code is making its way into production builds and I will get it removed.

Thanks!

**Comment by pke** [comment]
Thanks for you reply. Yes I was referring to the code that adds the debug styles. But I did not think of storybook. Does storybook usually use production code or does it use debug code? If its using debug builds then we could still wrap the debug code into `__DEV__` conditional blocks to remove the code from production builds.

**Comment by hirokazutei** [comment]
Sorry for the late reply again.

I think I understand now:
The intent of the `debug` code was meant for it to be a toggle prop in storybook, which can have production builds depending on the usage and preference of the user. But, outside of the context of Storybook, `debug` style is used in non-production builds to check out the spacing and it would be preferable if the `debug` style is automatically turned off in production builds.

I am not quite sure what would be the optimum solution to this would be, since wrapping it with `__DEV__` would do a disservice to users who are making production builds with storybook. What might be simple to do would be to prefix `debug` and `debugOptions` with an underscore to illustrate the fact that they are not regular props to be used in non-testing production builds.

What do you think?
Also, is there anything else you'd think could be added to the library?

**Comment by hirokazutei** [comment]
Sorry for the late reply again.

I think I understand now:
The intent of the `debug` code was meant for it to be a toggle prop in storybook, which can have production builds depending on the usage and preference of the user. But, outside of the context of Storybook, `debug` style is used in non-production builds to check out the spacing and it would be preferable if the `debug` style is automatically turned off in production builds.

I am not quite sure what would be the optimum solution to this would be, since wrapping it with `__DEV__` would do a disservice to users who are making production builds with storybook. What might be simple to do would be to prefix `debug` and `debugOptions` with an underscore to illustrate the fact that they are not regular props to be used in non-testing production builds.

Let me know what you think: @pke 
Also, is there anything else you'd like to see added to the library?

**Comment by pke** [comment]
No worries.
I didn't have the whole storybook issue on the radar. Do you have an example where people use the debug info?

**Comment by hirokazutei** [comment]
I don't have a particular example, but I recall being able to make storybook apps and have it viewable on your mobile device. Within the story, debug is toggled by an option.
If I recall correctly, `__DEV__` distinguishes if the app is running in a dev environment or not, not different types of builds, correct? If that is the case, would putting debug code behind `__DEV__` lock users out of being able to see debug styles on actual devices? @pke

**Comment by pke** [comment]
Ok that makes sense to toggle it from withing in the storybook story.

Code guarded by `__DEV__` is removed in react production builds. So if you deploy a debug/dev build on a device you will still see it. But standard testflight and certainly production builds will not contain this code anymore.

**Comment by hirokazutei** [comment]
If that is the case, I think removing `debug` should be fine.
Will do it tomorrow.

**Comment by hirokazutei** [comment]
@pke Sorry for taking so long.
Version `v1.2.0-rc.0` is release and it should no longer display `debug` views in production builds.
